version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    networks:
      - my-network

  frontend:
    build: ./client
    container_name: frontend
    depends_on:
      - backend
    command: 'npm run start'
    networks:
      - my-network

  backend:
    build: ./server
    container_name: backend
    networks:
      - my-network

networks:
  my-network: