version: '3'

services:
  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - '80:80'
    networks:
      - shared-network

  frontend:
    build: ./client
    container_name: nuxt-frontend
    depends_on:
      - backend
    command: 'npm run start'
    networks:
      - shared-network

  backend:
    build: ./server
    container_name: nest-backend
    networks:
      - shared-network

networks:
  shared-network: